import { Octokit } from '@octokit/rest'
import type { GeneratedProject } from '@/lib/codegen/generator'

function getOctokit(token?: string) {
  return new Octokit({ auth: token || process.env.GITHUB_TOKEN })
}

export async function createRepo(
  token: string | undefined,
  owner: string,
  repoName: string,
  description: string,
  isOrg: boolean = false
): Promise<{ url: string; cloneUrl: string }> {
  const octokit = getOctokit(token)
  const sanitizedName = repoName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-')

  let repo
  if (isOrg) {
    const result = await octokit.repos.createInOrg({
      org: owner,
      name: sanitizedName,
      description,
      private: false,
      auto_init: false,
    })
    repo = result.data
  } else {
    const result = await octokit.repos.createForAuthenticatedUser({
      name: sanitizedName,
      description,
      private: false,
      auto_init: false,
    })
    repo = result.data
  }

  return { url: repo.html_url, cloneUrl: repo.clone_url }
}

export async function pushProjectToGitHub(
  token: string | undefined,
  owner: string,
  repoName: string,
  project: GeneratedProject
): Promise<string> {
  const octokit = getOctokit(token)
  const sanitizedName = repoName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-')

  // Check if repo exists, create if not
  let repoExists = false
  try {
    await octokit.repos.get({ owner, repo: sanitizedName })
    repoExists = true
  } catch {}

  if (!repoExists) {
    try {
      // Try as org first
      await octokit.repos.createInOrg({
        org: owner,
        name: sanitizedName,
        description: project.description,
        private: false,
        auto_init: false,
      })
    } catch {
      await octokit.repos.createForAuthenticatedUser({
        name: sanitizedName,
        description: project.description,
        private: false,
        auto_init: false,
      })
    }
  }

  // Get or create main branch ref
  let sha: string | undefined
  try {
    const ref = await octokit.git.getRef({ owner, repo: sanitizedName, ref: 'heads/main' })
    sha = ref.data.object.sha
  } catch {}

  // Build tree blobs
  const blobs = await Promise.all(
    project.files.map(async (file) => {
      const blob = await octokit.git.createBlob({
        owner,
        repo: sanitizedName,
        content: Buffer.from(file.content).toString('base64'),
        encoding: 'base64',
      })
      return { path: file.path, mode: '100644' as const, type: 'blob' as const, sha: blob.data.sha }
    })
  )

  const tree = await octokit.git.createTree({
    owner,
    repo: sanitizedName,
    tree: blobs,
    ...(sha ? { base_tree: sha } : {}),
  })

  const commit = await octokit.git.createCommit({
    owner,
    repo: sanitizedName,
    message: `Initial project generated by ArdouraAI\n\n${project.description}`,
    tree: tree.data.sha,
    ...(sha ? { parents: [sha] } : { parents: [] }),
  })

  if (sha) {
    await octokit.git.updateRef({
      owner,
      repo: sanitizedName,
      ref: 'heads/main',
      sha: commit.data.sha,
    })
  } else {
    await octokit.git.createRef({
      owner,
      repo: sanitizedName,
      ref: 'refs/heads/main',
      sha: commit.data.sha,
    })
  }

  return `https://github.com/${owner}/${sanitizedName}`
}
